# Generated by Django 5.0.6 on 2024-06-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='tag',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
