# Generated by Django 5.0.6 on 2024-05-18 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dibujante',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsinc.project')),
            ],
        ),
    ]
