# Generated by Django 5.0.6 on 2024-05-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0002_project_dibujante_alter_project_name_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
