# Generated by Django 5.0.6 on 2024-07-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0003_sheet_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabs',
            name='chest_type',
            field=models.BooleanField(default=True),
        ),
    ]
