# Generated by Django 5.0.6 on 2024-05-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0004_project_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='approved',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
