# Generated by Django 5.0.6 on 2024-05-18 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0005_project_approved_project_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='approved',
            new_name='approved_by',
        ),
    ]
