# Generated by Django 5.0.6 on 2024-05-18 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0006_rename_approved_project_approved_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='approved_by',
            new_name='approved',
        ),
    ]
