# Generated by Django 5.0.6 on 2024-07-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0006_license_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='is_controller',
            field=models.BooleanField(default=False),
        ),
    ]
