# Generated by Django 5.0.6 on 2024-05-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0007_rename_approved_by_project_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='approved',
            field=models.CharField(max_length=200),
        ),
    ]
