# Generated by Django 5.0.6 on 2024-07-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0008_usd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('rate', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='USD',
        ),
    ]
