# Generated by Django 5.0.6 on 2024-07-10 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0009_badge_delete_usd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Divice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default=None, max_length=100)),
                ('brand', models.CharField(default=None, max_length=100)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divice', to='tsinc.sheet')),
            ],
        ),
    ]
