# Generated by Django 5.0.6 on 2024-07-10 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0010_divice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divice',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divice', to='tsinc.tabs'),
        ),
    ]
