# Generated by Django 5.0.6 on 2024-05-18 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0011_alter_project_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_brand', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_location', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=None, max_length=200)),
                ('product_name', models.CharField(default=None, max_length=200)),
                ('factory_ref', models.CharField(default=None, max_length=200)),
                ('model', models.CharField(default=None, max_length=200)),
                ('sale_price', models.FloatField()),
                ('iva', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Prod_brand_loc_qu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('note', models.CharField(default=None, max_length=200)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsinc.brand')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsinc.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsinc.product')),
            ],
        ),
    ]
