# Generated by Django 5.0.6 on 2024-07-10 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0011_alter_divice_sheet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='divice',
            old_name='sheet',
            new_name='tab',
        ),
    ]
