# Generated by Django 5.0.6 on 2024-05-20 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0012_brand_location_product_prod_brand_loc_qu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prod_brand_loc_qu',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='prod_brand_loc_qu',
            name='location',
        ),
        migrations.RemoveField(
            model_name='prod_brand_loc_qu',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.FloatField(default=None),
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='Prod_brand_loc_qu',
        ),
    ]
