# Generated by Django 5.0.6 on 2024-07-10 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0012_rename_sheet_divice_tab'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total_points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsinc.project')),
            ],
        ),
    ]
