# Generated by Django 5.0.6 on 2024-07-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0013_total_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='total_points',
            name='code',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
