# Generated by Django 5.0.6 on 2024-05-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0014_offers_units_alter_product_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='controller',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
