# Generated by Django 5.0.6 on 2024-07-10 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0014_total_points_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='total_points',
            old_name='code',
            new_name='sheet',
        ),
    ]
