# Generated by Django 5.0.6 on 2024-07-10 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0015_rename_code_total_points_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='divice',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tsinc.project'),
        ),
        migrations.AlterField(
            model_name='divice',
            name='tab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsinc.tabs'),
        ),
    ]
