# Generated by Django 5.0.6 on 2024-05-26 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0015_offers_controller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slots',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='tsinc.product'),
        ),
    ]
