# Generated by Django 5.0.6 on 2024-05-28 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0016_alter_slots_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(default=None, max_length=100)),
                ('width', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dasboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
                ('proyect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='tsinc.project')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_code', models.CharField(default=None, max_length=50)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to='tsinc.dasboard')),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panelitem', to='tsinc.panelitems')),
            ],
        ),
    ]
