# Generated by Django 5.0.6 on 2024-07-11 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0016_divice_project_alter_divice_tab'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license',
            old_name='ref',
            new_name='name',
        ),
    ]
