# Generated by Django 5.0.6 on 2024-05-28 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0017_panelitems_dasboard_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dasboard',
            name='proyect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='tsinc.project'),
        ),
    ]
