# Generated by Django 5.0.6 on 2024-07-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0017_rename_ref_license_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='divice',
            name='tag',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
