# Generated by Django 5.0.6 on 2024-05-28 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0018_alter_dasboard_proyect'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dasboard',
            old_name='proyect',
            new_name='project',
        ),
    ]
