# Generated by Django 5.0.6 on 2024-05-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0019_rename_proyect_dasboard_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='zindex',
            field=models.IntegerField(default=0),
        ),
    ]
