# Generated by Django 5.0.6 on 2024-07-11 21:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0019_alter_divice_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
                ('description', models.TextField(validators=[django.core.validators.MaxLengthValidator(500)])),
            ],
        ),
    ]
