# Generated by Django 5.0.6 on 2024-07-11 21:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0020_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(5000)]),
        ),
    ]
