# Generated by Django 5.0.6 on 2024-05-29 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0021_items_height_items_width'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_code', models.CharField(default=None, max_length=50)),
                ('value', models.CharField(default=None, max_length=200)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('zindex', models.IntegerField(default=0)),
                ('width', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='tsinc.dasboard')),
            ],
        ),
    ]
