# Generated by Django 5.0.6 on 2024-07-15 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0021_alter_note_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True, validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
    ]
