# Generated by Django 5.0.6 on 2024-05-30 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0022_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tsinc.product'),
        ),
    ]
