# Generated by Django 5.0.6 on 2024-07-16 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0023_project_nit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='controller',
        ),
    ]
