# Generated by Django 5.0.6 on 2024-07-16 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0024_remove_project_controller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Badge',
        ),
    ]
