# Generated by Django 5.0.6 on 2024-06-01 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0025_rename_sesionuser_project_usersesion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='product',
        ),
        migrations.AddField(
            model_name='panelitems',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tsinc.product'),
        ),
    ]
