# Generated by Django 5.0.6 on 2024-07-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0025_delete_badge'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
            ],
        ),
    ]
