# Generated by Django 5.0.6 on 2024-06-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0026_remove_items_product_panelitems_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='point',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
