# Generated by Django 5.0.6 on 2024-07-18 16:35

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0026_offercode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Remission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('nit', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('project', models.CharField(max_length=250)),
                ('responsible', models.CharField(max_length=200)),
                ('date', models.DateField(default=datetime.date.today)),
                ('usersession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsinc.product')),
                ('remission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tsinc.remission')),
            ],
        ),
        migrations.CreateModel(
            name='ProductBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsinc.product')),
                ('usersession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('remission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tsinc.remission')),
            ],
        ),
    ]
