# Generated by Django 5.0.6 on 2024-07-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0027_remission_productsent_productbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurcharseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('tracking', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
            ],
        ),
    ]
