# Generated by Django 5.0.6 on 2024-06-02 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0027_product_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabs',
            name='offer',
        ),
        migrations.AddField(
            model_name='tabs',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='tsinc.project'),
        ),
    ]
