# Generated by Django 5.0.6 on 2024-07-19 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0028_purcharseorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbox',
            name='remission',
        ),
        migrations.RemoveField(
            model_name='purcharseorder',
            name='price',
        ),
        migrations.RemoveField(
            model_name='purcharseorder',
            name='quantity',
        ),
        migrations.AddField(
            model_name='productbox',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tsinc.purcharseorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsinc.product')),
            ],
        ),
    ]
