# Generated by Django 5.0.6 on 2024-06-02 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0028_remove_tabs_offer_tabs_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dasboard',
            name='project',
        ),
        migrations.AddField(
            model_name='dasboard',
            name='tab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='tsinc.tabs'),
        ),
    ]
