# Generated by Django 5.0.6 on 2024-07-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0029_remove_productbox_remission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purcharseorder',
            name='avalible',
            field=models.BooleanField(default=False),
        ),
    ]
