# Generated by Django 5.0.6 on 2024-06-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0029_remove_dasboard_project_dasboard_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='dasboard',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
