# Generated by Django 5.0.6 on 2024-06-02 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0030_dasboard_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='approved',
            new_name='asesor',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='dibujante',
            new_name='company_name',
        ),
    ]
