# Generated by Django 5.0.6 on 2024-06-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0032_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='controller',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
