# Generated by Django 5.0.6 on 2024-07-22 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0032_alter_productbox_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbox',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
