# Generated by Django 5.0.6 on 2024-06-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0033_project_controller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='done',
        ),
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
