# Generated by Django 5.0.6 on 2024-07-22 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0033_productbox_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbox',
            name='date',
        ),
        migrations.AddField(
            model_name='purcharseorder',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
