# Generated by Django 5.0.6 on 2024-07-24 14:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0034_remove_productbox_date_purcharseorder_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.date.today)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsinc.purcharseorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsinc.product')),
            ],
        ),
    ]
