# Generated by Django 5.0.6 on 2024-06-06 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0034_remove_project_done_project_progress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offers',
        ),
    ]
