# Generated by Django 5.0.6 on 2024-06-06 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0035_delete_offers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slots',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='slots',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='tabunits',
            name='tab',
        ),
        migrations.DeleteModel(
            name='Units',
        ),
        migrations.DeleteModel(
            name='Slots',
        ),
        migrations.DeleteModel(
            name='TabUnits',
        ),
    ]
