# Generated by Django 5.0.6 on 2024-06-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0036_remove_slots_slot_remove_slots_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabs',
            name='controller',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
