# Generated by Django 5.0.6 on 2024-07-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0036_alter_orderentry_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderentry',
            name='leftover',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purcharseorder',
            name='total_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purcharseorder',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
