# Generated by Django 5.0.6 on 2024-07-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0037_orderentry_leftover_purcharseorder_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purcharseorder',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
