# Generated by Django 5.0.6 on 2024-06-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0037_tabs_controller'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='relationship',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
