# Generated by Django 5.0.6 on 2024-07-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0038_purcharseorder_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purcharseorder',
            name='avalible',
        ),
        migrations.RemoveField(
            model_name='purcharseorder',
            name='tracking',
        ),
        migrations.AddField(
            model_name='purcharseorder',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purcharseorder',
            name='cost_center',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='purcharseorder',
            name='customer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='purcharseorder',
            name='inspector',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='purcharseorder',
            name='nit',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purcharseorder',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purcharseorder',
            name='supervisor',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='purcharseorder',
            name='supplier',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
