# Generated by Django 5.0.6 on 2024-06-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0038_items_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelitems',
            name='tag',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
