# Generated by Django 5.0.6 on 2024-07-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0039_remove_purcharseorder_avalible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderentry',
            name='leftover',
        ),
        migrations.AddField(
            model_name='orderentry',
            name='Tracking',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
