# Generated by Django 5.0.6 on 2024-07-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0041_rename_tracking_orderentry_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='purcharseorder',
            name='trm',
            field=models.FloatField(default=0),
        ),
    ]
