# Generated by Django 5.0.6 on 2024-06-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0041_rename_cotegory_subcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.FloatField(default=0),
        ),
    ]
