# Generated by Django 5.0.6 on 2024-06-14 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0042_alter_product_sale_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panelitems',
            name='width',
        ),
    ]
