# Generated by Django 5.0.6 on 2024-06-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0043_remove_panelitems_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelitems',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
