# Generated by Django 5.0.6 on 2024-07-30 15:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0043_alter_orderentry_date_alter_purcharseorder_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderentry',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='purcharseorder',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
