# Generated by Django 5.0.6 on 2024-07-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0044_alter_orderentry_date_alter_purcharseorder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='offercode',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purcharseorder',
            name='unit',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
