# Generated by Django 5.0.6 on 2024-06-16 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0045_folders'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelitems',
            name='folders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='panelitems', to='tsinc.folders'),
        ),
    ]
