# Generated by Django 5.0.6 on 2024-07-30 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0045_offercode_name_purcharseorder_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purcharseorder',
            name='unit',
        ),
    ]
