# Generated by Django 5.0.6 on 2024-07-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0046_remove_purcharseorder_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderentry',
            name='added',
            field=models.BooleanField(default=False),
        ),
    ]
