# Generated by Django 5.0.6 on 2024-06-16 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0046_panelitems_folders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panelitems',
            old_name='folders',
            new_name='folder',
        ),
    ]
