# Generated by Django 5.0.6 on 2024-08-01 14:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0047_orderentry_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='remission',
            name='number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='remission',
            name='order_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='remission',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
