# Generated by Django 5.0.6 on 2024-06-16 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0047_rename_folders_panelitems_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelitems',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='tsinc.product'),
        ),
    ]
