# Generated by Django 5.0.6 on 2024-06-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0048_alter_panelitems_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='labels',
            name='relationship',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
