# Generated by Django 5.0.6 on 2024-08-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0049_productsent_discounted'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderentry',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
