# Generated by Django 5.0.6 on 2024-08-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0051_productsent_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderentry',
            name='price_u',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='productsent',
            name='price_u',
            field=models.FloatField(default=0),
        ),
    ]
