# Generated by Django 5.0.6 on 2024-08-02 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0052_orderentry_price_u_productsent_price_u'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderentry',
            name='price_u',
        ),
        migrations.RemoveField(
            model_name='productsent',
            name='price_u',
        ),
    ]
