# Generated by Django 5.0.6 on 2024-08-03 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0055_productstatictics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstatictics',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsinc.product'),
        ),
    ]
