# Generated by Django 5.0.6 on 2024-08-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0056_alter_productstatictics_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purcharse_price',
            field=models.FloatField(default=0),
        ),
    ]
