# Generated by Django 5.0.6 on 2024-08-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0057_product_purcharse_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remission',
            name='order_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
