# Generated by Django 5.0.6 on 2024-08-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0060_alter_product_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='observation',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
