# Generated by Django 5.0.6 on 2024-08-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0061_alter_product_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='purcharseorder',
            name='observation',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='remission',
            name='observation',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
