# Generated by Django 5.0.6 on 2024-08-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0062_purcharseorder_observation_remission_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='purcharseorder',
            name='currency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purcharseorder',
            name='tracking',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
