# Generated by Django 5.0.6 on 2024-08-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0063_purcharseorder_currency_purcharseorder_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purcharse_price_cop',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price_cop',
            field=models.FloatField(default=0),
        ),
    ]
