# Generated by Django 5.0.6 on 2024-08-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0064_product_purcharse_price_cop_product_sale_price_cop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=50)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
    ]
