# Generated by Django 5.0.6 on 2024-08-20 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0069_orderfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderfile',
            name='remission',
        ),
        migrations.AddField(
            model_name='orderfile',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tsinc.purcharseorder'),
        ),
    ]
