# Generated by Django 5.0.6 on 2024-08-21 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0072_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='ica_retentiton',
            new_name='ica_retention',
        ),
    ]
