# Generated by Django 5.0.6 on 2024-08-21 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0074_orderinvoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinvoice',
            old_name='total_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='orderinvoice',
            name='number',
        ),
    ]
