# Generated by Django 5.0.6 on 2024-08-21 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0075_rename_total_price_orderinvoice_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinvoice',
            old_name='price',
            new_name='value_paid',
        ),
    ]
