# Generated by Django 5.0.6 on 2024-08-22 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0077_folder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
