# Generated by Django 5.0.6 on 2024-08-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0078_delete_folder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.RemoveField(
            model_name='purcharseorder',
            name='trm',
        ),
        migrations.AddField(
            model_name='purcharseorder',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
