# Generated by Django 5.0.6 on 2024-08-27 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0079_alter_invoice_options_remove_purcharseorder_trm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remission',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='remission',
            name='r_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tsinc.project'),
        ),
    ]
