# Generated by Django 5.0.6 on 2024-08-27 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0080_remove_remission_project_project_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remission',
            name='r_project',
        ),
    ]
