# Generated by Django 5.0.6 on 2024-08-27 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0081_remove_remission_r_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='remission',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tsinc.project'),
        ),
    ]
