# Generated by Django 5.0.6 on 2024-08-29 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0087_alter_folder_project_alter_folder_usersession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='usersesion',
        ),
    ]
