# Generated by Django 5.0.6 on 2024-08-29 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0089_project_usersesion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='usersesion',
            new_name='usersession',
        ),
    ]
