# Generated by Django 5.0.6 on 2024-08-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0091_alter_invoice_usersession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remission',
            name='contruction_site',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='remission',
            name='supplier',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
