# Generated by Django 5.0.6 on 2024-09-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0093_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
