# Generated by Django 5.0.6 on 2024-09-03 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0095_file_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='order_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tsinc.orderinvoice'),
        ),
    ]
