# Generated by Django 5.0.6 on 2024-09-04 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0096_file_order_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='closing_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='project',
            name='code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='delivery_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
