# Generated by Django 5.0.6 on 2024-09-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0098_category_parent_category_tag_subcategory_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
