# Generated by Django 5.0.6 on 2024-09-06 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0099_alter_category_tag_delete_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('unit_value', models.FloatField(default=0)),
                ('total_value', models.FloatField(default=0)),
                ('section', models.IntegerField(default=0)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tsinc.product')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tsinc.project')),
                ('tab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tsinc.tabs')),
            ],
        ),
    ]
