# Generated by Django 5.0.6 on 2024-09-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0100_generatedoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedoffer',
            name='measure',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='generatedoffer',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='generatedoffer',
            name='total_value',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='generatedoffer',
            name='unit_value',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
