# Generated by Django 5.0.6 on 2024-09-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0102_generatedoffer_porcent'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedoffer',
            name='to_purcharse_order',
            field=models.BooleanField(default=False),
        ),
    ]
