# Generated by Django 5.0.6 on 2024-09-20 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0105_sheet_tab'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsinc.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsinc.product')),
            ],
        ),
    ]
