# Generated by Django 5.0.6 on 2024-09-23 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0107_productsent_section_productsent_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbox',
            name='section',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productbox',
            name='tab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tsinc.tabs'),
        ),
    ]
