# Generated by Django 5.0.6 on 2024-10-07 20:36

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0108_productbox_section_productbox_tab'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField(default=datetime.date.today)),
                ('estimated_time', models.TimeField(default=datetime.time(15, 36, 48, 525186))),
                ('priority', models.CharField(max_length=250)),
                ('percent_completed', models.IntegerField(default=0)),
                ('description', models.TextField(validators=[django.core.validators.MaxLengthValidator(5000)])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsinc.project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
