# Generated by Django 5.0.6 on 2024-10-12 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0109_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='measure',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_time',
            field=models.TimeField(default=datetime.time(8, 40, 33, 193767)),
        ),
    ]
