# Generated by Django 5.0.6 on 2024-10-16 22:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0112_generatedoffer_description_alter_task_estimated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedoffer',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tsinc.generatedoffer'),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_time',
            field=models.TimeField(default=datetime.time(17, 1, 6, 186840)),
        ),
    ]
