# Generated by Django 5.0.6 on 2024-10-17 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0113_generatedoffer_parent_alter_task_estimated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedoffer',
            name='is_title',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_time',
            field=models.TimeField(default=datetime.time(10, 27, 59, 72734)),
        ),
    ]
