# Generated by Django 5.0.6 on 2024-10-19 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0114_generatedoffer_is_title_alter_task_estimated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedoffer',
            name='is_subtotal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_time',
            field=models.TimeField(default=datetime.time(8, 19, 25, 299168)),
        ),
    ]
