# Generated by Django 5.0.6 on 2024-10-21 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0115_generatedoffer_is_subtotal_alter_task_estimated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated_time',
            field=models.TimeField(default=datetime.time(11, 32, 31, 873423)),
        ),
    ]
