# Generated by Django 5.0.6 on 2024-10-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0121_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='action',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
