# Generated by Django 5.0.6 on 2024-10-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0123_auditlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='item',
            new_name='model',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='project',
        ),
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
