# Generated by Django 5.0.6 on 2024-10-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0125_container'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='task',
        ),
        migrations.AddField(
            model_name='container',
            name='tasks',
            field=models.ManyToManyField(related_name='containers', to='tsinc.task'),
        ),
    ]
