# Generated by Django 5.0.6 on 2024-10-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0127_alter_container_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='tasks',
            field=models.ManyToManyField(related_name='containers', to='tsinc.task'),
        ),
    ]
