# Generated by Django 5.0.6 on 2024-10-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0128_alter_container_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='container',
            field=models.CharField(choices=[('conteiner1', 'Container1'), ('conteiner2', 'Container2'), ('conteiner3', 'Container3')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Container',
        ),
    ]
