# Generated by Django 5.0.6 on 2024-10-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0129_task_container_delete_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='container',
            field=models.CharField(choices=[('container1', 'Container1'), ('container2', 'Container2'), ('container3', 'Container3')], max_length=10, null=True),
        ),
    ]
