# Generated by Django 5.0.6 on 2024-10-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0131_task_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[(1, 'Pendiente'), (2, 'En proceso'), (3, 'Finalizado')], default='Pendiente', max_length=10, null=True),
        ),
    ]
