# Generated by Django 5.0.6 on 2024-10-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0132_alter_task_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en proceso', 'En proceso'), ('finalizado', 'Finalizado')], default='Pendiente', max_length=10, null=True),
        ),
    ]
