# Generated by Django 5.0.6 on 2024-10-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0133_alter_task_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='container',
            field=models.CharField(choices=[('container1', 'Container1'), ('container2', 'Container2'), ('container3', 'Container3')], default='container1', max_length=10, null=True),
        ),
    ]
