# Generated by Django 5.0.6 on 2024-10-29 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0139_taskfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskfile',
            old_name='product',
            new_name='task',
        ),
    ]
