# Generated by Django 5.0.6 on 2024-10-29 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0140_rename_product_taskfile_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tsinc.task'),
        ),
        migrations.DeleteModel(
            name='TaskFile',
        ),
    ]
