# Generated by Django 5.0.6 on 2025-05-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0143_project_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='archive_project',
            field=models.BooleanField(default=False),
        ),
    ]
