# Generated by Django 5.0.6 on 2025-05-04 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsinc', '0144_project_archive_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folders', to='tsinc.project'),
        ),
    ]
