from django.contrib import admin
from .models import *
# Register your models here.

models_ = [ Project,
            Brand,
            Location,
            Product,
            Tabs,
            Dasboard,
            PanelItems,
            Items,
            Labels,
            Category,
            Folders,
            Sheet,
            Points,
            License,
            Divice,
            Total_points,
            Note,
            OfferCode,
            Remission,
            ProductSent,
            ProductBox,
            PurcharseOrder,
            OrderProduct,
            OrderEntry,
            ProductStatictics,
            Trm,
            RemissionFile,
            OrderFile,
            ProductFile,
            Invoice,
            OrderInvoice,
            Folder,
            File,
            GeneratedOffer          
           ]
admin.site.register(models_)
